kestra-io/plugin-azure

- src/main/java/io/kestra/plugin/azure/cli/AzCLI.java
To explain how to authenticate
> Docs for Azure CLI

- gradle.properties
- src/main/java/io/kestra/plugin/azure/storage/blob/services/BlobService.java
- src/test/java/io/kestra/plugin/azure/BaseTest.java
- src/test/java/io/kestra/plugin/azure/storage/blob/AbstractTest.java
- src/test/java/io/kestra/plugin/azure/storage/blob/DownloadsTest.java
> fix: preserve file extension with the Download task

- .github/workflows/main.yml
- .gitignore
- src/test/java/io/kestra/plugin/azure/cli/AzCLITest.java
> chore: add a service principal to github and use it to test cli

- src/main/java/io/kestra/plugin/azure/eventhubs/Produce.java
> chore: rename input id to input name

- src/main/java/io/kestra/plugin/azure/storage/blob/abstracts/AbstractBlobStorage.java
- src/main/java/io/kestra/plugin/azure/storage/blob/models/BlobStorageForBatch.java
> fix: AbstractBlobStorage and BlobStorageForBatch are not tasks

- src/main/java/io/kestra/plugin/azure/batch/job/Create.java
- src/main/java/io/kestra/plugin/azure/runner/AzureBatchTaskRunner.java
> feat(runner): properly handle TaskRunner kill (#93)

- src/main/java/io/kestra/plugin/azure/storage/blob/Downloads.java
- src/test/java/io/kestra/plugin/azure/storage/blob/DownloadsTest.java
> feat: Add 'outputFiles' property with a map of file name / URI

- src/main/java/io/kestra/plugin/azure/storage/table/Bulk.java
> feat: Bulk - render the map

- src/main/java/io/kestra/plugin/azure/eventhubs/Consume.java
- src/main/java/io/kestra/plugin/azure/eventhubs/EventHubBatchConsumerInterface.java
- src/main/java/io/kestra/plugin/azure/eventhubs/EventHubConsumerInterface.java
- src/main/java/io/kestra/plugin/azure/eventhubs/RealtimeTrigger.java
- src/main/java/io/kestra/plugin/azure/eventhubs/Trigger.java
- src/main/java/io/kestra/plugin/azure/eventhubs/service/consumer/ConsumerContext.java
- src/main/java/io/kestra/plugin/azure/eventhubs/service/consumer/EventHubConsumerService.java
part-of: kestra-io/kestra#3767
> feat: enhance realtime trigger lifecycle

- src/main/java/io/kestra/plugin/azure/eventhubs/RealtimeTrigger.java
- src/main/java/io/kestra/plugin/azure/eventhubs/Trigger.java
Ensure there is a link/mention from Triggers to Realtime Triggers and vice versa
> fix(docs): add eventhubs realtime trigger description

- src/main/java/io/kestra/plugin/azure/eventhubs/AbstractEventHubTask.java
Getting this class in the Azure tasks as shown in the screesnshot:
> fix(code): make AbstractEventHubTask class abstract

- src/main/java/io/kestra/plugin/azure/batch/BatchService.java
- src/main/java/io/kestra/plugin/azure/batch/job/Create.java
- src/main/java/io/kestra/plugin/azure/batch/models/Job.java
- src/main/java/io/kestra/plugin/azure/batch/models/Task.java
- src/main/java/io/kestra/plugin/azure/runner/Batch.java
> feat: resume existing batch jobs

- build.gradle
Closes https://github.com/kestra-io/plugin-azure/pull/121
> chore: upgrade dependencies

- src/main/java/io/kestra/plugin/azure/datafactory/CreateRun.java
- src/test/java/io/kestra/plugin/azure/datafactory/CreateRunTest.java
> feat(data factory): add option to not wait pipeline

- src/main/java/io/kestra/plugin/azure/function/HttpFunction.java
- src/test/java/io/kestra/plugin/azure/function/HttpFunctionTest.java
updated tests
updated class names
replaced http by HTTP
> refactor: replace gson by jackson and rename class

- src/main/java/io/kestra/plugin/azure/storage/adls/Delete.java
- src/main/java/io/kestra/plugin/azure/storage/adls/Read.java
- src/main/java/io/kestra/plugin/azure/storage/adls/SharedAccess.java
- src/main/java/io/kestra/plugin/azure/storage/adls/Upload.java
- src/main/java/io/kestra/plugin/azure/storage/adls/abstracts/AbstractDataLakeWithFile.java
- src/main/java/io/kestra/plugin/azure/storage/adls/update/Append.java
- src/main/java/io/kestra/plugin/azure/storage/adls/update/Lease.java
- src/main/java/io/kestra/plugin/azure/storage/adls/update/SetAccessControl.java
- src/test/java/io/kestra/plugin/azure/storage/adls/AbstractTest.java
- src/test/java/io/kestra/plugin/azure/storage/adls/update/AppendTest.java
- src/test/java/io/kestra/plugin/azure/storage/adls/update/LeaseTest.java
- src/test/java/io/kestra/plugin/azure/storage/adls/update/SetAccessControlTest.java
refactor and move update tasks to update package
rename abstract class
> feat(adls): add SetAccessControl task

- src/main/java/io/kestra/plugin/azure/storage/blob/services/BlobService.java
> fix: StorageBlob List task resulting into erro

- src/main/java/io/kestra/plugin/azure/storage/adls/Trigger.java
- src/main/java/io/kestra/plugin/azure/storage/adls/models/AdlsFile.java
- src/main/java/io/kestra/plugin/azure/storage/adls/services/DataLakeService.java
- src/test/java/io/kestra/plugin/azure/storage/adls/TriggerTest.java
- src/test/resources/flows/adls-listen-delete-action.yaml
- src/test/resources/flows/adls-listen-move-action.yaml
add action Move and Delete for adls Trigger
refactor adls file output to have all the data needed
> feat(adls): add action MOVE and DELETE for adls Trigger

- .github/setup-unit.sh
> fix(ci): missing connection-string

- src/main/resources/doc/io.kestra.plugin.azure.md
> docs(): improve plugin docs

- src/main/java/io/kestra/plugin/azure/cli/package-info.java
- src/main/java/io/kestra/plugin/azure/storage/adls/package-info.java
- part of: https://github.com/kestra-io/kestra/issues/10631
> fix(): subgroups for better readability

- src/main/java/io/kestra/plugin/azure/eventhubs/Consume.java
- src/main/java/io/kestra/plugin/azure/eventhubs/Trigger.java
> fix(eventhub): handle required properties
